### ISSUE TITLE
HTTP ERROR 500 after login 

### ISSUE THREAD

**Issue by maheshgadgil7** [nathan242/ipcam-cctv#6]
http://mycam.unaux.com/

**Comment by nathan242** [comment]
Please check the web server error log to see if the PHP error has been logged. Post the errors here if you need help.

The host mycam.unaux.com has some exposed ports that probably shouldn't be. Please check/update the config if you have access to it. Also, http (unencrypted) should be disabled and only https used otherwise the login credentials and config could be captured.

**Comment by maheshgadgil7** [comment]
https://ipcam.fitzport.com/. same issue. there is nothing in the error log.

**Comment by nathan242** [comment]
Without the logs it is hard to say what the issue is. Also I would not recommend running this as a public site as this is intended to be ran on a server on a private secure network.

If you can get the logs it would also be good if you could provide the environment details (PHP version, PHP modules enabled, operating system).

**Comment by maheshgadgil7** [comment]
Warning: include(C:/xampp/htdocs/include/header.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\ipcam\index.php on line 28

Warning: include(): Failed opening 'C:/xampp/htdocs/include/header.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\ipcam\index.php on line 28

Warning: include(C:/xampp/htdocs/include/footer.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\ipcam\index.php on line 42

Warning: include(): Failed opening 'C:/xampp/htdocs/include/footer.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\ipcam\index.php on line 42

**Comment by nathan242** [comment]
Looks like this is running on a Windows based environment which is not supported. As per the README this is only supported on Linux and Unix like operating systems.

It may be possible to run the UI on a Windows environment but you will not be able to record from any devices as the scripts are not compatible.
